# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: zenform
email: yosuke.tamura+zenform@mixi.co.jp
description: >- # this means to ignore newlines until "baseurl:"
  zenform is a CLI tool to provision Zendesk instance automatically.
  It sends requests to Zendesk API based on your configuration files so that you can set up your Zendesk instance without manual operation on the web interface.
baseurl: "/zenform" # the subpath of your site, e.g. /blog
url: "https://xflagstudio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: xflagstudio/zenform

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemapgithub
  - jekyll-feed

include:
  - _pages
  - _docs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .gitignore
  - README.md

collections:
  docs:
    output: true

defaults:
  # pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true
      toc_label: " Contents"
      toc_icon: list

# site search
search: true

footer:
  links:
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/xflag_engineers"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/xflagstudio/zenform"
  - label: "Medium"
    icon: "fab fa-fw fa-medium"
    url: "https://medium.com/mixi-developers"
